apiVersion: v1
kind: Secret
metadata:
  name: dex-secret
  namespace: eoapi-dev
type: Opaque
stringData:
  client-secret: "<DEX_EOAPI_CLIENT_SECRET>"
  kservis-user-hash: "<BCRYPT_HASH_FOR_KSERVIS_PASSWORD>"
  noaa-reader-user-hash: "<BCRYPT_HASH_FOR_NOAA_READER_PASSWORD>"
