apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-dex-secret
  namespace: eoapi-dev
type: Opaque
stringData:
  client-id: "eoapi-dev"
  client-secret: "<DEX_EOAPI_CLIENT_SECRET>"
  cookie-secret: "<BASE64_URL_SAFE_COOKIE_SECRET>"
